### ISSUE TITLE
Armor not increasing AC and cannot be deleted

### ISSUE THREAD

**Issue by madseumas** [foundryvtt-dcc/dcc-content#1]
When adding armor to a character the AC does not increase and the armor item cannot be deleted.  Console log output attached in a screenshot.

No modules enabled other than the content module.

![dccbugreport](https://user-images.githubusercontent.com/6942993/113236764-2253b800-926b-11eb-805f-03369cef74e9.png)

**Comment by futurekill** [comment]
I'm on the same versions you are but I'm not having the deletion issue. I _was_ seeing the armor computation issue until I realized that the Compute AC option wasn't on (possible not on by default).
<img width="605" alt="compute_ac" src="https://user-images.githubusercontent.com/590852/113488277-f6168200-948a-11eb-9d56-575d97165636.png">

**Comment by futurekill** [comment]
As an aside, I think this question is more targeted to the DCC [system](https://github.com/foundryvtt-dcc/foundryvtt-dcc) as opposed to this repo.

**Comment by madseumas** [comment]
You're right on both counts, closing here.  Thanks!
