### ISSUE TITLE
Armors from the core book module missing movement penalty

### ISSUE THREAD

**Issue by RKober2112** [foundryvtt-dcc/dcc-content#14]
The armors from the core book compendium are missing the penalties for movement. 

![image](https://user-images.githubusercontent.com/82335198/115170005-f40d0f80-a095-11eb-93cb-1167a71908c2.png)

**Comment by algnc** [comment]
@mooped this looks to be becasuse typing -5' in the window changes it to -0. -5 works though.

**Comment by mooped** [comment]
I fixed this for movement speeds on the actor sheet. We can apply the same fix here. :)

**Comment by mooped** [comment]
This has been fixed in the system and core book dev branches and will come out with the next (non-hotfix) release.

**Comment by mooped** [comment]
These fixes are in the latest release.
