### ISSUE TITLE
No Spell Attack Roll from Wizard Spells Tab

### ISSUE THREAD

**Issue by mudpyr8** [foundryvtt-dcc/dcc-content#16]
Using the Hunter Wizard from the high level pregens 
Open the Wizard Spells tab
Click on the d20 roll button
Nothing happens

Equipment rolls seem fine, but spells don't roll. I tested with the Elf too and got the same thing.

**Comment by algnc** [comment]
Can't reproduce this issue. Can we get more details? Are any errors in the console? You own dcc-core, and it's enabled, right?

**Comment by mudpyr8** [comment]
Yes. I'll test again running in a different browser.

**Comment by mudpyr8** [comment]
I created a new world and everything worked. It must have been adding the content to an existing DCC world in Foundry was an issue. All set. Thank you for the response. Great job on the content!
