### ISSUE TITLE
Mummy missing 'club' attack

### ISSUE THREAD

**Issue by cyface** [foundryvtt-dcc/dcc-content#17]
The mummy has a 'club' attack that isn't set up on the Actor.

![image](https://user-images.githubusercontent.com/49695/119265164-f8e84600-bba2-11eb-88a6-d9a26c6fe502.png)
![image](https://user-images.githubusercontent.com/49695/119265181-04d40800-bba3-11eb-8423-6b5a1e25bd89.png)

**Comment by algnc** [comment]
fixed on fix-mummy-club

**Comment by cyface** [comment]
@mooped can we merge this one in?

**Comment by mooped** [comment]
No problem. I've just merged it.
