### ISSUE TITLE
Core Book NPC Attacks Don't Use Image When Dragged

### ISSUE THREAD

**Issue by cyface** [foundryvtt-dcc/dcc-content#18]
For NPC Actors in the Core Book module, when you drag their melee attacks to the macro bar, they don't use the 'weapon' image, they just show as generic macros.  Ranged attacks work fine (see 'King' for a ranged attack that works).

![image](https://user-images.githubusercontent.com/49695/119265296-68f6cc00-bba3-11eb-8247-b9c7667f4107.png)
![image](https://user-images.githubusercontent.com/49695/119265303-71e79d80-bba3-11eb-84ce-78bc797e81df.png)

**Comment by mooped** [comment]
The code that selects an appropriate image for the macro if none is present is unintentionally conditional on it being ranged. This is a holdover from where we picked one of two default images.

This is fixed on the 0.28.0 branch (first FVTT 0.8.5 release) so I'm going to close this. I don't think it requires any changes to the core book module unless we decide (as a feature) to assign custom icons to all NPC attacks in which case this becomes a non-issue anyway.
