### ISSUE TITLE
manifest.json URL is incorrect

### ISSUE THREAD

**Issue by widget** [foundryvtt-dcc/dcc-content#19]
I activated my compendium licence a few minutes ago and the manifest licence URL is `https://github.com/foundryvtt-dcc/dcc-content/blob/main/dcc-core-book/v0.90.3/module.json` and not `https://raw.githubusercontent.com/foundryvtt-dcc/dcc-content/main/dcc-core-book/module.json`.  The former is the HTML and not the raw JSON.

This is in Foundry 0.7.10 but I verified this with `curl`.

**Comment by heliobolseiro** [comment]
The same thing happened to me! I used both 0.7.9 and 0.7.10.

**Comment by mooped** [comment]
@cyface did this get fixed up?

**Comment by cyface** [comment]
@mooped I assume so!

**Comment by mooped** [comment]
Great. Closing. :)
