### ISSUE TITLE
Markup typo in Core Book Text at Introduction entry

### ISSUE THREAD

**Issue by jgbell** [foundryvtt-dcc/dcc-content#2]
In Core Book Text, Introduction entry; in the Core Mechanic section:

Occasionally a character may roll a die other than [[/roll 1d20]] when acting. [[/roll 1d16]], [[/roll 1d24]], and even [[/roll 1d3]]0 are used for weaker or stronger warriors and spellcasters.

should be:

Occasionally a character may roll a die other than [[/roll 1d20]] when acting. [[/roll 1d16]], [[/roll 1d24]], and even [[/roll 1d30]] are used for weaker or stronger warriors and spellcasters.

<img width="779" alt="Screen Shot 2021-04-02 at 8 40 16 AM" src="https://user-images.githubusercontent.com/28059012/113420961-de0e0800-938f-11eb-9c3a-0c3f4ff02f6e.png">

<img width="141" alt="Screen Shot 2021-04-02 at 8 40 30 AM" src="https://user-images.githubusercontent.com/28059012/113420977-e5351600-938f-11eb-910a-05957de9dca8.png">

**Comment by jgbell** [comment]
Note also in the image of the formatted entry I included, as an aside, on the FoundryVTT app on macOS, the headline font text "THE CORE MECHANIC" is clipped at the top of every page. It appears there's not enough line height for the font.

**Comment by cyface** [comment]
@jgbell are you on Mac? I think I noticed this line-height issue with the headline text on Mac, but it seems OK on PC. 🤔

**Comment by jgbell** [comment]
@cyface Yes, as mentioned in my previous this was "on the FoundryVTT app on macOS" 11.2.3 where I saw that behaviour. I can check with various combinations of browser, but only have macOS and Raspian at hand. Odd if just that one, but I will see and report back if I can find that it replicates across tools, or if it is specific to the app and macOS alone.

**Comment by cyface** [comment]
Pushed a fix for the mac side of this in https://github.com/foundryvtt-dcc/foundryvtt-dcc/pull/220 , so once we do the next system release that part of it should be fixed.
