### ISSUE TITLE
Clicking Luck on the Character Sheet doesn't add the modifier.

### ISSUE THREAD

**Issue by OregonPinkRose** [foundryvtt-dcc/dcc-content#20]

**Comment by OregonPinkRose** [comment]
When I create an actor I get a basic character sheet.
When I input 18 in the Luck attribute, it shows +3.
If I click Luck, it rolls a Luck Check in chat but doesn't add the +3.
Reproducible with any number and multiple characters.
Always doesn't work.

(If you click the modifier box, the +3, it does add it.)

**Comment by algnc** [comment]
Luck checks are roll under.

**Comment by OregonPinkRose** [comment]
Oh Right. 
I was just checking out the sheet and Luck was different then the rest.
