### ISSUE TITLE
The 2-11 option is repeated for Azi Dahaka

### ISSUE THREAD

**Issue by OregonPinkRose** [foundryvtt-dcc/dcc-content#21]
Azi Dahaka in Core Journals

The 2-11 option is repeated at the end of the paragraph

![chrome_2021-06-19_13-38-32](https://user-images.githubusercontent.com/17410871/122654992-e4e12700-d103-11eb-85ff-122ed3dc8ffb.png)

**Comment by algnc** [comment]
Fixed in fix-wizard-saves

**Comment by mooped** [comment]
Fix merged into main and dev branch.
