### ISSUE TITLE
Problem loading " 1- The Ruined Keep"

### ISSUE THREAD

**Issue by cleverername** [foundryvtt-dcc/dcc-content#26]
When I tried to load this scene The progress bar freezes at 90% and then the whole browser locks up. 

Tried deleting scened and re-installing from compendium

Last entries in Debugger are: 

foundry.js:22945 Foundry VTT | Loaded icons/svg/downgrade.svg (100%)
foundry.js:20576 Foundry VTT | Initializing Canvas culling using ScreenCulling backend

**Comment by algnc** [comment]
Loads OK for me, what is your setup like? It sounds like a system/Foundry issue.

**Comment by cleverername** [comment]
Running on Forge, current version.

**Comment by cleverername** [comment]
It was some strange add-on module conflict. I disabled all but DCC compedium and the "Sailors" module and it worked. 

Strangely, after adding them back in, one by one. It still works.

**Comment by cleverername** [comment]
Interestingly, all the actor and journal entries are broken in that scene.

**Comment by Portacustos1** [comment]
I've the same issue, came here looking for an answer. I launched in safe mode and it worked fine, so there must be a module conflict I'm guessing. Although it's almost 5AM here so I'm giving up for tonight. I've attached a list of the modules I have running, I don't know if @cleverername can export his list so we can see the crossovers?

Sadly it completely crashes the tab, so Find The Culprit module wont work.

I will get round to turning them on one-by-one manually to see where the issue is, but any help would be appreciated :)

[DCC Active Modules.txt](https://github.com/foundryvtt-dcc/dcc-content/files/8094081/DCC.Active.Modules.txt)

**Comment by Portacustos1** [comment]
Also, here's a screenshot of where it gets stuck in the console:

![image](https://user-images.githubusercontent.com/85347717/154618531-3ab51a8b-7be7-4a5e-bb83-6e3f21e2b32b.png)

**Comment by algnc** [comment]
@Portacustos1 are you also on the Forge?

**Comment by Portacustos1** [comment]
yeah, I'm also on The Forge, Fooundry v9, build 249 and using system Dungeon Crawl Classics v 0.33.2

**Comment by Portacustos1** [comment]
I can also make a new scene with the same details (copy/paste from one config to another) and it works fine - that may be my lazy workaround.

I'm guessing a journal note on the scene is causing the error, but I've turned off any modules I can think of like Pin Cushion that is journal note-altering

**Comment by algnc** [comment]
I'd like to help troubleshoot but this seems very specific to this setup / modules. Do you think you can narrow it down to the offender and let us know, then we can talk with the module dev?

**Comment by mooped** [comment]
@Portacustos1 thanks for the list.

You can hunt down this sort of problem without Find The Culprit by doing a binary chop:

- Split the list into two even halfs, pick half of it to enable and try loading the scene.
- If the problem goes away that half of the list isn't the problem, so switch to the other half of the list
- If the problem persists then repeat the process taking the enabled modules as a new list and splitting it in half, repeating the process again.

This gets you down to a single culprit very quickly.

In this case it seems to be FXMaster, we'll investigate and see what we find.

**Comment by algnc** [comment]
@Portacustos1  think we have found the issue. working on a fix now.

**Comment by Portacustos1** [comment]
oh that's great :) I was just going to log on and try and figure out the culprit, but looks like I've been beaten to it!

This is absolutely why I love the Foundry community, on another vtt this would never have been figured out overnight.

**Comment by cleverername** [comment]
It is working. The only issue is that all the actor and journal entries are broken in that scene. Not a huge deal, I can re-create them. 
Thanks!

**Comment by mooped** [comment]
> It is working. The only issue is that all the actor and journal entries are broken in that scene. Not a huge deal, I can re-create them. Thanks!

Unfortunately Foundry doesn't save the links in a way that they survive being exported to a compendium. We get around this by fixing up the links when the content importer runs.

If you dragged the scene in from the Compendium they will be broken.

The simplest way to reimport if the actors and journals are still in the folders they were imported to is to delete the scenes folder and re-run the Content Importer (you might need to enable Show Welcome Dialog on Startup in the module's settings) and just check the scenes folders. That should relink everything in the scenes correctly.
