### ISSUE TITLE
Journals need a clean-up and update for v10

### ISSUE THREAD

**Issue by monkey-bars** [foundryvtt-dcc/dcc-content#29]
Might not be worth doing until they get a proper table editor in the text editor, but the journals could really use a clean-up. I'd be happy to volunteer my services, if I can figure out how to get into the files, or if there's a test world I can edit them in.

**Comment by algnc** [comment]
What kind of cleanup are you looking for?

**Comment by monkey-bars** [comment]
Just general formatting and organization based on the new v10 book and pages-style journal.
