### ISSUE TITLE
Precalculated hit points for actors don't make sense

### ISSUE THREAD

**Issue by futurekill** [foundryvtt-dcc/dcc-content#3]
It looks like the HP for actors in the compendium are per-calculated which makes for some oddness. For example, "Bandits" (1d8 HD) in my compendium have 7 HP. Bandit Heroes (2d8 HD) have 5 HP.

<img width="603" alt="bandit" src="https://user-images.githubusercontent.com/590852/113465938-b5c0f080-9405-11eb-8417-354f44980f51.png">
<img width="602" alt="bandit_hero" src="https://user-images.githubusercontent.com/590852/113465939-b6598700-9405-11eb-8261-f3066fc72aae.png">

**Comment by algnc** [comment]
Fixed in dcc-core-book #104
