### ISSUE TITLE
DCC CORE BOOK V1.0.6 link is broken - Table 1-10: Warrior

### ISSUE THREAD

**Issue by sasquach45932** [foundryvtt-dcc/dcc-content#33]
Hello,

In the compendium index the link is broken Table 1-10: Warrior. See the attached screenshot.

![DCC](https://github.com/foundryvtt-dcc/dcc-content/assets/92884040/7abd7531-1b59-4fc6-9d6e-541eeef90b6e)

BR,

SasQ

**Comment by cyface** [comment]
Fixed in v1.1.3.
