### ISSUE TITLE
Misfire table for wizard casting versions of cleric spells should point to major corruption table

### ISSUE THREAD

**Issue by kobush** [foundryvtt-dcc/dcc-content#35]
Wizard versions of the cleric spells (Detect Magic, Binding, Detect Evil, Paralysis) currently point to the Greater Corruption table but the footnote under Table 5-8 on p. 127, and spell result for 1  state to roll on the Major Corruption table.

**Comment by cyface** [comment]
Fixed in v1.1.3.
