### ISSUE TITLE
Spell Check misleading Typo

### ISSUE THREAD

**Issue by sdubein** [foundryvtt-dcc/dcc-content#39]
I was checking the Core Book Text in Foundry VTT DCC Compendium and the Typo that existed in the 8th printing of DCC is present in the Chapter 5 "Spell Checks" section.

Currently it reads:

> When your character casts a spell, you roll 1d20 and add your caster level, _and apply your luck modifier._  

This was changed to:

> When your character casts a spell, you roll 1d20 and add your caster level. 

In later printings.

**Comment by cyface** [comment]
Fixed in v1.1.3.
