### ISSUE TITLE
Certain spell tables lack inline rolls

### ISSUE THREAD

**Issue by VerdantCoding** [foundryvtt-dcc/dcc-content#7]
Some spells in the DCC core rulebook module lack inline rolls in some entries for misfires and/or results. I've chosen to focus on spells where the roll isn't modified by CL, since those are the ones that seem to be supposed to be inline. These are the spells I've been able to find with this issue, after going through every Wizard, Cleric, and Patron spell:
- Flaming Hands
- Animal Summoning
- Charm Person
- Chill Touch
- Choking Cloud
- Color Spray
- Comprehend Languages
- Detect Magic (Wizard Casting)
- Ekim's Mystical Mask
- Enlarge
- Feather Fall
- Find Familiar
- Force Manipulation
- Invoke Patron
- Magic Missile
- Mending
- Read Magic
- Ropework
- Ventriloquism
- Ward Portal
- Detect Invisible
- Invisible Companion
- Magic Mouth
- Monster Summoning
- Nythuul's Porcupine
- Ray of Enfeeblement
- Scorching Ray
- Spider Web
- Strength
- Breathe Life
- Consult Spirit
- Dispel Magic
- Fireball
- Fly
- Haste
- Lightning Bolt
- Make Potion
- Planar Step
- Slow
- Water Breathing
- Control Fire
- Control Ice
- Polymorph
- Hepsoj's Fecund Fungi

**Comment by algnc** [comment]
This also includes Misfires, Corruption, etc.

**Comment by algnc** [comment]
Some of the misfire/corruption results aren't CL, they are just regular dice.

**Comment by mooped** [comment]
Fixed in Core Book v0.90.2.
